---
name: Apache2-AutoIndex-XSLT
version: 0.01
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
abstract: XSLT Based Directory Listings
license: open_source
requires:
  Apache2::Access: 0
  Apache2::CmdParms: 0
  Apache2::Const: 0
  Apache2::Log: 0
  Apache2::Module: 0
  Apache2::RequestRec: 0
  Apache2::RequestUtil: 0
  Apache2::ServerRec: 0
  Apache2::ServerUtil: 0
  Apache2::URI: 0
  Apache2::Util: 0
  Fcntl: 0
  File::Spec: 0
  URI::Escape: 0
  XML::Quote: 0
build_requires:
  Test: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Apache2::AutoIndex::XSLT:
    file: lib/Apache2/AutoIndex/XSLT.pm
    version: 0.01
